In [ ]:
import numpy as np
import random

##Практическая часть

In [884]:
dataset = list()

dataset.append(([0, 0],0))
dataset.append(([0, 1],1))
dataset.append(([1, 0],1))
dataset.append(([1, 1],1))

In [885]:
import copy
import random
noise_dataset = list()
for i in range(10000):
  noise_dataset.append(copy.deepcopy(random.choice(dataset)))
  for j in range(2):
    noise_dataset[i][0][j] += (random.randint(-45, 45) * 0.01)

In [886]:
random.choice(noise_dataset)

([0.64, 0.0], 1)

In [887]:
first_layer_weights = np.ones((2, 1))

In [888]:
first_layer_weights

array([[1.],
       [1.]])

In [889]:
def result_bin_class(result):
  if (result > 1):
    return True
  else:
    return False

In [890]:
def calculate_res(input_number, first_layer_weights):
  sum = 0
  for i in range(2):
    sum += input_number[0][i//2] * first_layer_weights[i]
  return sum

In [891]:
def weight_changing(positive, target):
  k = 0
  if (positive and not target):
    k = -0.1
  elif (not positive and target):
    k = 0.1
  return k

In [892]:
dataset2 = list()
for i in range(10000):
  dataset2.append(random.choice(dataset))

In [893]:
dataset2

[([1, 1], 1),
 ([1, 1], 1),
 ([1, 1], 1),
 ([1, 1], 1),
 ([0, 0], 0),
 ([1, 1], 1),
 ([1, 0], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([0, 0], 0),
 ([1, 0], 1),
 ([0, 0], 0),
 ([1, 1], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([1, 1], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([1, 1], 1),
 ([0, 1], 1),
 ([0, 0], 0),
 ([1, 0], 1),
 ([1, 0], 1),
 ([1, 0], 1),
 ([1, 0], 1),
 ([1, 0], 1),
 ([1, 1], 1),
 ([1, 1], 1),
 ([0, 0], 0),
 ([1, 1], 1),
 ([0, 1], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([0, 1], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([0, 0], 0),
 ([0, 0], 0),
 ([0, 0], 0),
 ([1, 1], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([1, 0], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([0, 0], 0),
 ([1, 1], 1),
 ([0, 1], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([0, 1], 1),
 ([1, 0], 1),
 ([1, 0], 1),
 ([1, 1], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([0, 1], 1),
 ([1, 0], 1),
 ([1, 1], 1),
 ([1, 1], 1),
 ([0, 

In [894]:

def learn(input_number, first_layer_weights, target):
    k = weight_changing(result_bin_class(calculate_res(input_number, first_layer_weights)),
                        True if input_number[1] == target else False)
    for i in range(2):
        first_layer_weights[i] += input_number[0][i // 2] * k
    return first_layer_weights

In [895]:
def train_nn(input_dataset, first_layer_weights, target, size_of_data):
  for i in range(size_of_data):
    first_layer_weights = learn(random.choice(input_dataset), first_layer_weights, target)

In [896]:
first_layer_weights

array([[1.],
       [1.]])

In [907]:
train_nn(dataset, first_layer_weights, 1, 200)

In [898]:
first_layer_weights

array([[1.],
       [1.]])

In [899]:
def test(input_number, first_layer_weights, target):
  if (result_bin_class(calculate_res(input_number, first_layer_weights)) == (True if input_number[1] == target else False)):
    return 1
  else:
    return 0

In [900]:
def test_nn(input_dataset, first_layer_weights, target, size_of_data):
  res = 0
  for i in range(size_of_data):
    res += test(random.choice(input_dataset), first_layer_weights, target)
  return (res / size_of_data)

In [901]:
first_layer_weights

array([[1.],
       [1.]])

In [908]:
print('Accuracy-score: ', test_nn(noise_dataset, first_layer_weights,1, 800))

Accuracy-score:  0.7875
