In [436]:
import numpy as np
import random

##Практическая часть

In [437]:
dataset = list()

dataset.append(([0, 0],0))
dataset.append(([0, 1],1))
dataset.append(([1, 0],1))
dataset.append(([1, 1],1))

In [438]:
import copy
import random
noise_dataset = list()
for i in range(10000):
  noise_dataset.append(copy.deepcopy(random.choice(dataset)))
  for j in range(2):
    noise_dataset[i][0][j] += (random.randint(-45, 45) * 0.01)

In [439]:
random.choice(noise_dataset)

([-0.1, 1.32], 1)

In [440]:
first_layer_weights = np.ones((2, 1))

In [441]:
first_layer_weights

array([[1.],
       [1.]])

In [442]:
def result_bin_class(result):
  if (result > 0.8):
    return True
  else:
    return False

In [443]:
for i in range(2):
    print(i)

0
1


In [444]:
def calculate_res(input_number, first_layer_weights):
  sum = 0
  for i in range(2):
    sum += input_number[0][i] * first_layer_weights[i]
  return sum

In [445]:
def weight_changing(positive, target):
  k = 0
  if (positive and not target):
    k = -0.1
  elif (not positive and target):
    k = 0.1
  return k

In [446]:
dataset2 = list()
for i in range(10000):
  dataset2.append(random.choice(dataset))

In [447]:
dataset2

[([1, 1], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([0, 1], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([1, 0], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([0, 1], 1),
 ([0, 0], 0),
 ([0, 1], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([1, 1], 1),
 ([1, 1], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([1, 1], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([1, 1], 1),
 ([1, 1], 1),
 ([1, 1], 1),
 ([1, 1], 1),
 ([0, 0], 0),
 ([1, 0], 1),
 ([1, 0], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([1, 1], 1),
 ([1, 0], 1),
 ([0, 1], 1),
 ([0, 0], 0),
 ([1, 0], 1),
 ([1, 0], 1),
 ([1, 1], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([1, 1], 1),
 ([1, 0], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([1, 0], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([1, 1], 1),
 ([1, 1], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([1, 0], 1),
 ([1, 0], 1),
 ([1, 1], 1),
 ([1, 0], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([0, 

In [448]:

def learn(input_number, first_layer_weights, target):
    k = weight_changing(result_bin_class(calculate_res(input_number, first_layer_weights)),
                        True if input_number[1] == target else False)
    for i in range(2):
        first_layer_weights[i] += input_number[0][i] * k
    return first_layer_weights

In [449]:
def train_nn(input_dataset, first_layer_weights, target, size_of_data):
  for i in range(size_of_data):
    first_layer_weights = learn(random.choice(input_dataset), first_layer_weights, target)

In [450]:
first_layer_weights

array([[1.],
       [1.]])

In [463]:
train_nn(dataset2, first_layer_weights,1, 10000)

In [452]:
first_layer_weights

array([[1.],
       [1.]])

In [453]:
def test(input_number, first_layer_weights, target):
  if (result_bin_class(calculate_res(input_number, first_layer_weights)) == (True if input_number[1] == target else False)):
    return 1
  else:
    return 0

In [454]:
def test_nn(input_dataset, first_layer_weights, target, size_of_data):
  res = 0
  for i in range(size_of_data):
    res += test(random.choice(input_dataset), first_layer_weights, target)
  return (res / size_of_data)

In [455]:
first_layer_weights

array([[1.],
       [1.]])

In [456]:
noise_dataset

[([0.55, 0.28], 1),
 ([0.8200000000000001, -0.09], 1),
 ([0.06, 0.41000000000000003], 0),
 ([-0.29, -0.14], 0),
 ([0.38, 0.88], 1),
 ([-0.23, 1.08], 1),
 ([0.05, 0.74], 1),
 ([1.02, 0.07], 1),
 ([0.24, 0.44], 0),
 ([0.06, -0.18], 0),
 ([0.1, 0.8200000000000001], 1),
 ([-0.29, 0.9299999999999999], 1),
 ([0.22, 0.09], 0),
 ([0.79, 0.99], 1),
 ([0.06, 0.89], 1),
 ([1.29, 0.87], 1),
 ([-0.43, -0.26], 0),
 ([0.6499999999999999, -0.26], 1),
 ([0.88, -0.05], 1),
 ([-0.35000000000000003, 1.35], 1),
 ([0.27, 1.26], 1),
 ([1.13, 0.8], 1),
 ([-0.02, 0.6699999999999999], 1),
 ([1.45, 0.76], 1),
 ([0.95, -0.23], 1),
 ([-0.19, -0.27], 0),
 ([0.55, 0.12], 1),
 ([0.12, 0.75], 1),
 ([-0.01, 0.74], 1),
 ([-0.31, -0.05], 0),
 ([0.87, 1.32], 1),
 ([0.36, -0.29], 0),
 ([1.29, 0.7], 1),
 ([1.17, 1.43], 1),
 ([1.3599999999999999, 1.4100000000000001], 1),
 ([0.78, 0.92], 1),
 ([1.23, 0.77], 1),
 ([1.37, 1.32], 1),
 ([0.28, -0.12], 0),
 ([0.98, 0.72], 1),
 ([-0.19, -0.08], 0),
 ([-0.45, 0.0], 0),
 ([0.22, 0.04

In [464]:
print('Accuracy-score: ', test_nn(noise_dataset, first_layer_weights,1, 1000))

Accuracy-score:  0.832
