In [244]:
import numpy as np
import random

##Практическая часть

In [245]:
dataset = list()

dataset.append(([0, 0],0))
dataset.append(([0, 1],1))
dataset.append(([1, 0],1))
dataset.append(([1, 1],1))

In [246]:
import copy
import random
noise_dataset = list()
for i in range(10000):
  noise_dataset.append(copy.deepcopy(random.choice(dataset)))
  for j in range(2):
    noise_dataset[i][0][j] += (random.randint(-45, 45) * 0.01)

In [247]:
random.choice(noise_dataset)

([-0.25, 0.31], 0)

In [270]:
first_layer_weights = np.ones((2, 1))

In [269]:
first_layer_weights

array([[0.2],
       [0.2]])

In [250]:
def result_bin_class(result):
  if (result > 0.5):
    return True
  else:
    return False

In [251]:
for i in range(2):
    print(i)

0
1


In [252]:
def calculate_res(input_number, first_layer_weights):
  sum = 0
  print("_______________________________________________________________________________")
  for i in range(2):
    if input_number[0][i] < 0:
      sum=sum
      print("Меньше 0 ",sum," int_num_for_i = ",i," :",input_number[0][i])
    else:
      sum += input_number[0][i] * first_layer_weights[i]
      print("Не меньше 0 ",sum," int_num_for_i = ",i," :",input_number[0][i])
  return sum

In [253]:
def weight_changing(positive, target):
  k = 0
  if (positive and not target):
    k = -0.1
  elif (not positive and target):
    k = 0.1
  return k

In [254]:
dataset2 = list()
for i in range(10000):
  dataset2.append(random.choice(dataset))

In [255]:
dataset2

[([0, 1], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([0, 0], 0),
 ([0, 1], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([1, 0], 1),
 ([1, 0], 1),
 ([0, 1], 1),
 ([1, 0], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([1, 1], 1),
 ([0, 0], 0),
 ([0, 1], 1),
 ([0, 0], 0),
 ([1, 0], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([0, 0], 0),
 ([0, 1], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([0, 0], 0),
 ([1, 1], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([1, 0], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([1, 0], 1),
 ([0, 0], 0),
 ([1, 1], 1),
 ([0, 1], 1),
 ([1, 0], 1),
 ([1, 1], 1),
 ([0, 0], 0),
 ([1, 0], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([0, 0], 0),
 ([0, 1], 1),
 ([1, 0], 1),
 ([0, 1], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([1, 1], 1),
 ([0, 0], 0),
 ([0, 0], 0),
 ([0, 0], 0),
 ([1, 0], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([0, 1], 1),
 ([1, 1], 1),
 ([0, 1], 1),
 ([1, 0], 1),
 ([1, 0], 1),
 ([0, 1], 1),
 ([1, 0], 1),
 ([1, 1], 1),
 ([0, 

In [256]:

def learn(input_number, first_layer_weights, target):
    k = weight_changing(result_bin_class(calculate_res(input_number, first_layer_weights)),
                        True if input_number[1] == target else False)
    for i in range(2):
        first_layer_weights[i] += input_number[0][i] * k
    return first_layer_weights

In [257]:
def train_nn(input_dataset, first_layer_weights, target, size_of_data):
  for i in range(size_of_data):
    first_layer_weights = learn(random.choice(input_dataset), first_layer_weights, target)

In [258]:
first_layer_weights

array([[1.],
       [1.]])

In [275]:
train_nn(dataset2, first_layer_weights,1, 10000)

_______________________________________________________________________________
Не меньше 0  [1.]  int_num_for_i =  0  : 1
Не меньше 0  [2.]  int_num_for_i =  1  : 1
_______________________________________________________________________________
Не меньше 0  [1.]  int_num_for_i =  0  : 1
Не меньше 0  [1.]  int_num_for_i =  1  : 0
_______________________________________________________________________________
Не меньше 0  [0.]  int_num_for_i =  0  : 0
Не меньше 0  [0.]  int_num_for_i =  1  : 0
_______________________________________________________________________________
Не меньше 0  [0.]  int_num_for_i =  0  : 0
Не меньше 0  [1.]  int_num_for_i =  1  : 1
_______________________________________________________________________________
Не меньше 0  [0.]  int_num_for_i =  0  : 0
Не меньше 0  [0.]  int_num_for_i =  1  : 0
_______________________________________________________________________________
Не меньше 0  [0.]  int_num_for_i =  0  : 0
Не меньше 0  [1.]  int_num_for_i =  1  : 1
____

In [260]:
first_layer_weights

array([[1.],
       [1.]])

In [261]:
def test(input_number, first_layer_weights, target):
  if (result_bin_class(calculate_res(input_number, first_layer_weights)) == (True if input_number[1] == target else False)):
    return 1
  else:
    return 0

In [262]:
def test_nn(input_dataset, first_layer_weights, target, size_of_data):
  res = 0
  for i in range(size_of_data):
    res += test(random.choice(input_dataset), first_layer_weights, target)
  return (res / size_of_data)

In [263]:
first_layer_weights

array([[1.],
       [1.]])

In [264]:
noise_dataset

[([0.77, 0.1], 1),
 ([1.16, -0.21], 1),
 ([-0.09, -0.2], 0),
 ([0.74, 1.31], 1),
 ([0.0, 0.06], 0),
 ([1.11, 1.3599999999999999], 1),
 ([0.37, 0.74], 1),
 ([-0.4, 1.45], 1),
 ([0.78, 0.13], 1),
 ([0.06, 1.09], 1),
 ([0.9, -0.37], 1),
 ([0.2, 1.4], 1),
 ([0.14, 0.87], 1),
 ([-0.39, 0.77], 1),
 ([0.05, 0.69], 1),
 ([0.2, 0.02], 0),
 ([1.03, 0.86], 1),
 ([-0.34, 0.12], 0),
 ([0.39, 0.85], 1),
 ([0.38, -0.18], 0),
 ([1.1400000000000001, 1.05], 1),
 ([0.01, 0.43], 0),
 ([1.23, 1.44], 1),
 ([-0.21, 0.45], 0),
 ([-0.29, 1.29], 1),
 ([-0.45, 0.63], 1),
 ([-0.06, 0.69], 1),
 ([1.1, 1.45], 1),
 ([1.37, -0.02], 1),
 ([0.73, 0.27], 1),
 ([0.39, 0.07], 0),
 ([-0.32, 1.37], 1),
 ([0.34, 1.17], 1),
 ([0.86, 1.3900000000000001], 1),
 ([0.33, 0.75], 1),
 ([0.88, 0.6], 1),
 ([0.8200000000000001, 0.09], 1),
 ([0.04, 1.07], 1),
 ([1.45, 0.03], 1),
 ([0.41000000000000003, -0.14], 0),
 ([-0.05, 0.83], 1),
 ([0.0, 0.84], 1),
 ([1.3900000000000001, 0.94], 1),
 ([1.3599999999999999, 0.8], 1),
 ([0.0, 1.1400000

In [281]:
print('Accuracy-score: ', test_nn(noise_dataset, first_layer_weights,1, 1000))

_______________________________________________________________________________
Не меньше 0  [0.85]  int_num_for_i =  0  : 0.85
Не меньше 0  [1.44]  int_num_for_i =  1  : 0.59
_______________________________________________________________________________
Меньше 0  0  int_num_for_i =  0  : -0.3
Меньше 0  0  int_num_for_i =  1  : -0.37
_______________________________________________________________________________
Не меньше 0  [0.6]  int_num_for_i =  0  : 0.6
Не меньше 0  [1.94]  int_num_for_i =  1  : 1.34
_______________________________________________________________________________
Не меньше 0  [0.85]  int_num_for_i =  0  : 0.85
Не меньше 0  [1.12]  int_num_for_i =  1  : 0.27
_______________________________________________________________________________
Меньше 0  0  int_num_for_i =  0  : -0.45
Не меньше 0  [0.97]  int_num_for_i =  1  : 0.97
_______________________________________________________________________________
Меньше 0  0  int_num_for_i =  0  : -0.26
Не меньше 0  [0.04]  in